# Generated by Django 4.2.6 on 2024-05-23 02:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_tag_painting_vote_score_painting_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='painting',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
