# Generated by Django 4.2.6 on 2024-05-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('paintings', '0003_painting_featured_image_alter_painting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
