# Generated by Django 4.2.6 on 2024-05-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_alter_painting_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[(1, 'Just Pass👌🏼'), (2, 'Nice👍'), (3, 'Look Good!😍'), (4, 'Wonderful!🤩')], max_length=200),
        ),
    ]
