# Generated by Django 4.2.6 on 2024-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_alter_review_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('Just Pass👌🏼', 1), ('Nice👍', 2), ('Look Good!😍', 3), ('Wonderful!🤩', 4)], max_length=200),
        ),
    ]
