# Generated by Django 4.2.6 on 2024-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_alter_review_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['-vote_score', '-vote_total', 'title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('1', 'Just Pass👌🏼'), ('2', 'Nice👍'), ('3', 'Look Good!😍'), ('4', 'Wonderful!🤩')], max_length=200),
        ),
    ]
